# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

d_ed <- function(x, y, TT) {
    .Call(`_classrepr_d_ed`, x, y, TT)
}

sgn0 <- function(x) {
    .Call(`_classrepr_sgn0`, x)
}

red_rld <- function(x) {
    .Call(`_classrepr_red_rld`, x)
}

