# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

d_qed <- function(x, y, TT, bsf) {
    .Call('_classrepr_d_qed', PACKAGE = 'classrepr', x, y, TT, bsf)
}

sgn0 <- function(x) {
    .Call('_classrepr_sgn0', PACKAGE = 'classrepr', x)
}

red_rld <- function(x) {
    .Call('_classrepr_red_rld', PACKAGE = 'classrepr', x)
}

